export default {
  // navbar: "#cfe1b9",
  // background: "#e9f5db",
  // feedItem: "#cfe1b9",
  navbar: "#e9edc9",
  background: "#fefae0",
  table: "#faedcd",
  button: "#fefae0",
  field: "#faedcd",
  circle1: "#d8f3dc",
  circle2: "#cfe1b9",
  rough: "#40916c",
  fairway: "#74c69d",
  ob: "#e07a5f",
};
