GET http://localhost:5000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjkyZGUzOTYzLWRhMTItNDUzOS05ZWI1LTQ0MTgyOTFmOWJmMyIsIm5iZiI6MTU4NzM4MzYxMywiZXhwIjoxNTg3OTg4NDEzLCJpYXQiOjE1ODczODM2MTN9.VXOKAvCK-F6n9kUdDCOGMOzvr-F8xMpZAiC2l5UqA0I


###
POST http://localhost:5000/api/users/authenticate
content-type: application/json

{
    "username": "kofoed",
    "password": "password"
}